### ISSUE TITLE
How to include in theme

### ISSUE THREAD

**Issue by saffa803** [MickeyKay/better-font-awesome-library#2]
Hi,

Thanks for a great plugin.

How do you include the better font awesome library in a custom wordpress theme as I've followed the instructions in the readme but nothing is happening, i.e No tinymce button, etc.

**Comment by MickeyKay** [comment]
Can you include the code you're using? Did you follow the download instructions in the readme file that explain how to download and install the submodules that are included?

**Comment by saffa803** [comment]
I cloned the library into my theme and installed the submodules as required.

This is the code I added to my functions:

// Include the main library file. Make sure to modify the path to match your directory structure.
require_once ( dirname( __FILE__ ) . '/better-font-awesome-library/better-font-awesome-library.php' );

add_action( 'plugins_loaded', 'my_prefix_load_bfa' );
/**
 * Initialize the Better Font Awesome Library.
 *
 * (see usage notes below on proper hook priority)
 */
function my_prefix_load_bfa() {

    // Set the library initialization args (defaults shown).
    $args = array(
            'version' => 'latest',
            'minified' => true,
            'remove_existing_fa' => false,
            'load_styles'             => true,
            'load_admin_styles'       => true,
            'load_shortcode'          => true,
            'load_tinymce_plugin'     => true,
    );

    // Initialize the Better Font Awesome Library.
    Better_Font_Awesome_Library::get_instance( $args );
}

Do I need to include the Wordpress plugin in my theme as well?

**Comment by MickeyKay** [comment]
Hmm, I'm not sure why this would be failing. Is the BFA Library included in the same directory as the file from which you're calling these functions? Any chance you could send me a copy of your theme to test?

**Comment by saffa803** [comment]
Whats the best way to send you the theme?

**Comment by MickeyKay** [comment]
You can just email me at mickeyskay@gmail.com.

**Comment by EidrianGM** [comment]
If it helps to anyone. Do not forget to install and activate the wordpress plugin after following all the instructions in installation.
