### ISSUE TITLE
CDN Assets Have Moved

### ISSUE THREAD

**Issue by cgrymala** [MickeyKay/better-font-awesome-library#22]
If you look at https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md#550-to-560 you'll see that the CDN assets have moved since this library was last updated. Instead of the icons.yml file being located in `advanced-options/metadata/icons.yml` it's now located at `metadata/icons.yml`, which is causing this library not to be able to locate the icon data.

As far as I can tell, the only change that needs to be made is to modify https://github.com/MickeyKay/better-font-awesome-library/blob/master/better-font-awesome-library.php#L70 from:

```php
	const JSDELIVR_ICON_METADATA_FILE_PATH = '/advanced-options/metadata/icons.yml';
```

to:

```php
	const JSDELIVR_ICON_METADATA_FILE_PATH = '/metadata/icons.yml';
```

Thanks.

**Comment by cgrymala** [comment]
Actually, since it only moved after v5.5.0, it would probably need to do some sort of version comparison before defining the constant.

**Comment by MickeyKay** [comment]
@cgrymala Wow, juuuuust seeing this. So sorry for the delay my friend :( On the positive side, though, I'm happy to announce I've got a PR in the works to fix #allthethings, and simply use the latest version of FA always. I'd love your eyes if you have a moment: https://github.com/MickeyKay/better-font-awesome/pull/17
